//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENTİTİYprojeuygulama
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblsatiş
    {
        public int SATİŞAD { get; set; }
        public Nullable<int> URUN { get; set; }
        public Nullable<int> MUSTERİ { get; set; }
        public Nullable<decimal> FİYAT { get; set; }
        public Nullable<System.DateTime> TARİH { get; set; }
    
        public virtual tblmusteri tblmusteri { get; set; }
        public virtual tblurun tblurun { get; set; }
    }
}
